import React, { useEffect } from 'react';
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";


export default function PrivacyPolicy() {
    useEffect(() => {
        window.scrollTo(0, 0);
      }, []);
    return (
        <>
            <Navbar mode="dark" />
            <div className="min-h-screen bg-white">
                <div className="max-w-4xl mx-auto px-4 py-16 mt-12">
                    <h1 className="text-4xl font-medium text-center mb-8">Privacy Policy</h1>
                    <p className="text-gray-500 text-center mb-16">Last updated: November 18, 2022</p>

                    <div className="prose max-w-none">
                        {/* Introduction */}
                        <div className="mb-12">
                            <p className="text-gray-600 mb-4">
                                This Privacy Policy describes Our policies and procedures on the collection, use and disclosure of Your information when You use the Service and tells You about Your privacy rights and how the law protects You.
                            </p>
                            <p className="text-gray-600">
                                We use Your Personal data to provide and improve the Service. By using the Service, You agree to the collection and use of information in accordance with this Privacy Policy.
                            </p>
                        </div>

                        {/* Interpretation and Definitions */}
                        <div className="mb-12">
                            <h2 className="text-2xl font-bold mb-6">Interpretation and Definitions</h2>
                            
                            <div className="mb-8">
                                <h3 className="text-xl font-semibold mb-4">Interpretation</h3>
                                <p className="text-gray-600">
                                    The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.
                                </p>
                            </div>

                            <div>
                                <h3 className="text-xl font-semibold mb-4">Definitions</h3>
                                <div className="bg-gray-50 p-6 rounded-lg">
                                    <ul className="space-y-4">
                                        {[
                                            { term: "Account", definition: "means a unique account created for You to access our Service or parts of our Service." },
                                            { term: "Company", definition: "(referred to as either \"the Company\", \"We\", \"Us\" or \"Our\" in this Agreement) refers to Electric Power Conversions Australia (EPCA), WA 6101." },
                                            { term: "Cookies", definition: "are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses." },
                                            { term: "Country", definition: "refers to: Australia" },
                                            { term: "Device", definition: "means any device that can access the Service such as a computer, a cellphone or a digital tablet." },
                                            { term: "Personal Data", definition: "is any information that relates to an identified or identifiable individual." },
                                            { term: "Service", definition: "refers to the Website." },
                                            { term: "Service Provider", definition: "means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used." },
                                            { term: "Third-party Social Media Service", definition: "refers to any website or any social network website through which a User can log in or create an account to use the Service." },
                                            { term: "Usage Data", definition: "refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit)." },
                                            { term: "Website", definition: "refers to EPCA, accessible from https://epca.net.au/" },
                                            { term: "You", definition: "means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable." }
                                        ].map((item, index) => (
                                            <li key={index} className="flex flex-col">
                                                <span className="font-medium text-gray-900">{item.term}</span>
                                                <span className="text-gray-600">{item.definition}</span>
                                            </li>
                                        ))}
                                    </ul>
                                </div>
                            </div>
                        </div>

                        {/* Collecting and Using Personal Data */}
                        <div className="mb-12">
                            <h2 className="text-2xl font-bold mb-6">Collecting and Using Your Personal Data</h2>
                            
                            <div className="mb-8">
                                <h3 className="text-xl font-semibold mb-4">Types of Data Collected</h3>
                                
                                <div className="space-y-8">
                                    <div>
                                        <h4 className="text-lg font-medium mb-4">Personal Data</h4>
                                        <p className="text-gray-600 mb-4">
                                            While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:
                                        </p>
                                        <ul className="list-disc list-inside text-gray-600 ml-4 space-y-2">
                                            <li>Email address</li>
                                            <li>First name and last name</li>
                                            <li>Phone number</li>
                                            <li>Address, State, Province, ZIP/Postal code, City</li>
                                            <li>Usage Data</li>
                                        </ul>
                                    </div>

                                    <div>
                                        <h4 className="text-lg font-medium mb-4">Usage Data</h4>
                                        <p className="text-gray-600 mb-4">
                                            Usage Data is collected automatically when using the Service.
                                        </p>
                                        <p className="text-gray-600 mb-4">
                                            Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data.
                                        </p>
                                        <p className="text-gray-600 mb-4">
                                            When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.
                                        </p>
                                        <p className="text-gray-600">
                                            We may also collect information that Your browser sends whenever You visit our Service or when You access the Service by or through a mobile device.
                                        </p>
                                    </div>
                                </div>
                            </div>

                            {/* Tracking Technologies and Cookies */}
                            <div className="mb-8">
                                <h3 className="text-xl font-semibold mb-4">Tracking Technologies and Cookies</h3>
                                <p className="text-gray-600 mb-6">
                                    We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to improve and analyze Our Service.
                                </p>

                                <div className="bg-gray-50 p-6 rounded-lg mb-8">
                                    <h4 className="text-lg font-medium mb-4">Technologies We Use:</h4>
                                    <ul className="space-y-6">
                                        <li>
                                            <span className="font-medium text-gray-900">Cookies or Browser Cookies</span>
                                            <p className="text-gray-600 mt-2">
                                                A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.
                                            </p>
                                        </li>
                                        <li>
                                            <span className="font-medium text-gray-900">Flash Cookies</span>
                                            <p className="text-gray-600 mt-2">
                                                Certain features of our Service may use local stored objects (or Flash Cookies) to collect and store information about Your preferences or Your activity on our Service. Flash Cookies are not managed by the same browser settings as those used for Browser Cookies.
                                            </p>
                                        </li>
                                        <li>
                                            <span className="font-medium text-gray-900">Web Beacons</span>
                                            <p className="text-gray-600 mt-2">
                                                Certain sections of our Service and our emails may contain small electronic files known as web beacons that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics.
                                            </p>
                                        </li>
                                    </ul>
                                </div>

                                <div className="bg-gray-50 p-6 rounded-lg">
                                    <h4 className="text-lg font-medium mb-4">Types of Cookies We Use:</h4>
                                    <ul className="space-y-6">
                                        <li>
                                            <span className="font-medium text-gray-900">Necessary / Essential Cookies</span>
                                            <p className="text-gray-600 mt-2">Type: Session Cookies</p>
                                            <p className="text-gray-600">Administered by: Us</p>
                                            <p className="text-gray-600 mt-2">
                                                These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We only use these Cookies to provide You with those services.
                                            </p>
                                        </li>
                                        <li>
                                            <span className="font-medium text-gray-900">Cookies Policy / Notice Acceptance Cookies</span>
                                            <p className="text-gray-600 mt-1">Type: Persistent Cookies</p>
                                            <p className="text-gray-600">Administered by: Us</p>
                                            <p className="text-gray-600 mt-2">
                                                These Cookies identify if users have accepted the use of cookies on the Website.
                                            </p>
                                        </li>
                                        <li>
                                            <span className="font-medium text-gray-900">Functionality Cookies</span>
                                            <p className="text-gray-600 mt-1">Type: Persistent Cookies</p>
                                            <p className="text-gray-600">Administered by: Us</p>
                                            <p className="text-gray-600 mt-2">
                                                These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference. The purpose of these Cookies is to provide You with a more personal experience and to avoid You having to re-enter your preferences every time You use the Website.
                                            </p>
                                        </li>
                                    </ul>
                                </div>
                            </div>

                            {/* Use of Personal Data */}
                            <div className="mb-12">
                                <h3 className="text-xl font-semibold mb-4">Use of Your Personal Data</h3>
                                <p className="text-gray-600 mb-4">The Company may use Personal Data for the following purposes:</p>
                                <ul className="list-disc list-inside text-gray-600 space-y-2 mb-6">
                                    <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
                                    <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
                                    <li>For the performance of a contract: the development, compliance and undertaking of the purchase contract for the products, items or services You have purchased or of any other contract with Us through the Service.</li>
                                    <li>To contact You: By email, telephone calls, SMS, or other equivalent forms of electronic communication.</li>
                                    <li>To provide You with news, special offers and general information about other goods, services and events.</li>
                                    <li>To manage Your requests: To attend and manage Your requests to Us.</li>
                                    <li>For business transfers: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets.</li>
                                    <li>For other purposes: We may use Your information for other purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience.</li>
                                </ul>
                            </div>

                            {/* Sharing Personal Data */}
                            <div className="mb-12">
                                <h3 className="text-xl font-semibold mb-4">Sharing Your Personal Data</h3>
                                <p className="text-gray-600 mb-4">We may share Your personal information in the following situations:</p>
                                <ul className="list-disc list-inside text-gray-600 space-y-2">
                                    <li>With Service Providers: To monitor and analyze the use of our Service, to contact You.</li>
                                    <li>For business transfers: In connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition.</li>
                                    <li>With Affiliates: With Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
                                    <li>With business partners: To offer You certain products, services or promotions.</li>
                                    <li>With other users: When You share personal information or otherwise interact in the public areas with other users.</li>
                                    <li>With Your consent: We may disclose Your personal information for any other purpose with Your consent.</li>
                                </ul>
                            </div>

                            {/* Retention and Transfer of Personal Data */}
                            <div className="mb-12">
                                <h3 className="text-xl font-semibold mb-4">Retention of Your Personal Data</h3>
                                <p className="text-gray-600 mb-8">
                                    The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
                                </p>

                                <h3 className="text-xl font-semibold mb-4">Transfer of Your Personal Data</h3>
                                <p className="text-gray-600 mb-4">
                                    Your information, including Personal Data, is processed at the Company's operating offices and in any other places where the parties involved in the processing are located. It means that this information may be transferred to — and maintained on — computers located outside of Your state, province, country or other governmental jurisdiction where the data protection laws may differ than those from Your jurisdiction.
                                </p>
                                <p className="text-gray-600">
                                    Your consent to this Privacy Policy followed by Your submission of such information represents Your agreement to that transfer.
                                </p>
                            </div>

                            {/* Disclosure of Personal Data */}
                            <div className="mb-12">
                                <h3 className="text-xl font-semibold mb-4">Disclosure of Your Personal Data</h3>
                                
                                <div className="space-y-6">
                                    <div>
                                        <h4 className="text-lg font-medium mb-2">Business Transactions</h4>
                                        <p className="text-gray-600">
                                            If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred. We will provide notice before Your Personal Data is transferred and becomes subject to a different Privacy Policy.
                                        </p>
                                    </div>

                                    <div>
                                        <h4 className="text-lg font-medium mb-2">Law enforcement</h4>
                                        <p className="text-gray-600">
                                            Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.
                                        </p>
                                    </div>

                                    <div>
                                        <h4 className="text-lg font-medium mb-2">Other legal requirements</h4>
                                        <p className="text-gray-600 mb-4">
                                            The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
                                        </p>
                                        <ul className="list-disc list-inside text-gray-600 space-y-2">
                                            <li>Comply with a legal obligation</li>
                                            <li>Protect and defend the rights or property of the Company</li>
                                            <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
                                            <li>Protect the personal safety of Users of the Service or the public</li>
                                            <li>Protect against legal liability</li>
                                        </ul>
                                    </div>
                                </div>
                            </div>

                            {/* Security and Links */}
                            <div className="mb-12">
                                <h3 className="text-xl font-semibold mb-4">Security of Your Personal Data</h3>
                                <p className="text-gray-600 mb-8">
                                    The security of Your Personal Data is important to Us, but remember that no method of transmission over the Internet, or method of electronic storage is 100% secure. While We strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
                                </p>

                                <h3 className="text-xl font-semibold mb-4">Links to Other Websites</h3>
                                <p className="text-gray-600 mb-4">
                                    Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy of every site You visit.
                                </p>
                                <p className="text-gray-600">
                                    We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.
                                </p>
                            </div>

                            {/* Changes to Privacy Policy */}
                            <div className="mb-12">
                                <h3 className="text-xl font-semibold mb-4">Changes to this Privacy Policy</h3>
                                <p className="text-gray-600 mb-4">
                                    We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page.
                                </p>
                                <p className="text-gray-600 mb-4">
                                    We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the "Last updated" date at the top of this Privacy Policy.
                                </p>
                                <p className="text-gray-600">
                                    You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy are effective when they are posted on this page.
                                </p>
                            </div>

                            {/* Contact Section */}
                            <div className="bg-gray-50 border-l-4 border-[#00CC66] p-6 rounded-lg">
                                <h3 className="text-xl font-semibold mb-4">Contact Us</h3>
                                <p className="text-gray-600 mb-2">
                                    If you have any questions about this Privacy Policy, you can email us at <a href="mailto:clayton.franklin@epca.net.au" className="text-[#00CC66] hover:underline">clayton.franklin@epca.net.au.</a>
                                </p>
                                {/* <p className="text-gray-600">
                                    By email: <a href="mailto:clayton.franklin@epca.net.au" className="text-[#00CC66] hover:underline">clayton.franklin@epca.net.au</a>
                                </p> */}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <Footer />
        </>
    );
}